### PR TITLE
Improved user interface of python binding

### PR DESCRIPTION
**Pull request by berndgassmann**
This change is [Reviewable](https://reviewable.io/reviews/carla-simulator/map/23)

### CODE REVIEW

**Review by fabianoboril — DISMISSED** [review]
> Reviewed 23 of 23 files at r1.
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/map/23)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @felipecode)

**Review by berndgassmann — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/map/23)* status: all files reviewed, 1 unresolved discussion (waiting on @felipecode)

___
*[ad_map_access/python/CMakeLists.txt, line 48 at r1](https://reviewable.io/reviews/carla-simulator/map/23#-MFpIt1oDKu6DsYRqix6:-MFpIt1p1-cGeCtfmyBx:bsqeyc3) ([raw file](https://github.com/carla-simulator/map/blob/5b495615ca3ec2a879899ae7ffba1b04ea88f457/ad_map_access/python/CMakeLists.txt#L48)):*
> ```CMake
>     configure_file(ad/map/component/__init__.py.in ${binding}/ad/map/${component}/__init__.py)
> 
>     add_library(${target} SHARED
> ```

Splitting up the libraries with static compilation has the drawback, that the singletons of ad::map are not working anymore!
Every portion of the python library has it's own singleton. Urgh!

Need to combine all the files to one single so but keeping the module structure within!

**Review by berndgassmann — COMMENTED** [review]
> Reviewed 5 of 6 files at r2.
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/map/23)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @felipecode)

**Comment by felipecode** [comment]
It worked fine, it just found a small documentation.

https://github.com/carla-simulator/map/blob/improve_python_user_interface/doc/BUILDING.md

the new PROJ dependency is uppercase

**Comment by fabianoboril** [comment]
Before merging, we should look into #25

**Review by fabianoboril — APPROVED** [review]
> Reviewed 8 of 22 files at r4, 13 of 13 files at r5.
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/map/23)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @felipecode)

**Pull request merged**
