### PR TITLE
Python wheels for AD Map library

### PR DESCRIPTION
**Pull request by joel-mb**
This PR is a first iteration for building and publishing python wheels for the `ad_physics` and `ad_map_access` packages:
* Supported python versions: `2.7`, `3.6`, `3.7`, `3.8`
* Dropped support for building python bindings for several versions at the same time ( the `BUILD_PYTHON_BINDING` cmake parameter has been replaced by `PYTHON_BINDING_VERSION`).
* The wheels are generated inside a docker container with all the necessary dependencies (https://hub.docker.com/repository/docker/joelmb/map). (Note: Docker images should be moved to the official CARLA dockerhub).

For testing purposes, the packages have been already published in the `TestPyPI` repository:
* `ad-physics`: https://test.pypi.org/project/ad-physics
* `ad-map-access`: https://test.pypi.org/project/ad-map-access

To install them, just run the following commands (requires `pip>=20.3`):
```sh
pip install -i https://test.pypi.org/simple/ ad-physics
pip install -i https://test.pypi.org/simple/ ad-map-access
```

---
This change is [Reviewable](https://reviewable.io/reviews/carla-simulator/map/60)

### CODE REVIEW

**Review by berndgassmann — COMMENTED** [review]
> Reviewed 16 of 16 files at r1, 19 of 19 files at r2.
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/map/60)* status: all files reviewed, 1 unresolved discussion (waiting on @joel-mb)

___
*[ad_map_access/python/CMakeLists.txt, line 62 at r2](https://reviewable.io/reviews/carla-simulator/map/60#-MeePSZT2dNc_l4hFSza:-MeePSZUCEq-9xMq3ID4:b-8jphnh) ([raw file](https://github.com/carla-simulator/map/blob/26c61050983641119ab000484c9d5ed569579a59/ad_map_access/python/CMakeLists.txt#L62)):*
> ```CMake
>   PRIVATE
>   ${PYTHON_BINDING_PACKAGE_INCLUDE_DIRS}
>   ${AD_PHYSICS_PYTHON_INCLUDES}
> ```

to be removed

**Review by fabianoboril — COMMENTED** [review]
> Reviewed 6 of 16 files at r1, 16 of 19 files at r2, 7 of 7 files at r3.
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/map/60)* status: all files reviewed, 4 unresolved discussions (waiting on @joel-mb)

___
*[.github/workflows/wheels.yml, line 14 at r3](https://reviewable.io/reviews/carla-simulator/map/60#-Mehp8Yt9vWf-1S1R-92:-Mehp8Yt9vWf-1S1R-93:b1fjdez) ([raw file](https://github.com/carla-simulator/map/blob/47721b96e71ba652b21e165df3a8d531319f3b00/.github/workflows/wheels.yml#L14)):*
> ```YAML
>         python_binding_version: [2.7, 3.6, 3.7, 3.8]
>     container:
>       image: joelmb/map:${{ matrix.python_binding_version }}
> ```

Do we need a custom container image?
___
*[.github/workflows/wheels.yml, line 35 at r3](https://reviewable.io/reviews/carla-simulator/map/60#-MehpClX7RkW6YXjWjqk:-MehpClX7RkW6YXjWjql:b4h6ujg) ([raw file](https://github.com/carla-simulator/map/blob/47721b96e71ba652b21e165df3a8d531319f3b00/.github/workflows/wheels.yml#L35)):*
> ```YAML
>             auditwheel repair $whl --plat ${WHEEL_PLATFORM} --wheel-dir wheelhouse
>           done
>       # - name: Publish wheels to PyPI
> ```

If we do not want to publish the wheels, we might also just publish them here and have automatic downloads in CARLA?
___
*[docker/Dockerfile, line 1 at r3](https://reviewable.io/reviews/carla-simulator/map/60#-Mehpypz9IC2b5RdRGIb:-Mehpypz9IC2b5RdRGIc:b-gznoqw) ([raw file](https://github.com/carla-simulator/map/blob/47721b96e71ba652b21e165df3a8d531319f3b00/docker/Dockerfile#L1)):*
> ```Dockerfile
> ARG PYTHON_BINDING_VERSION
> ```

This docker is only required for building as part of the github actions, or not? Maybe move to the github folder in this case

**Review by joel-mb — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/map/60)* status: 21 of 29 files reviewed, 4 unresolved discussions (waiting on @berndgassmann, @fabianoboril, and @joel-mb)

___
*[.github/workflows/wheels.yml, line 14 at r3](https://reviewable.io/reviews/carla-simulator/map/60#-Mehp8Yt9vWf-1S1R-92:-MejaJ0RC8gDD-HvfxMF:b-j7jxwa) ([raw file](https://github.com/carla-simulator/map/blob/47721b96e71ba652b21e165df3a8d531319f3b00/.github/workflows/wheels.yml#L14)):*
<details><summary><i>Previously, fabianoboril (Fabian Oboril) wrote…</i></summary><blockquote>

Do we need a custom container image?
</blockquote></details>

I created custom container images to avoid having to install all the dependencies during runtime. Also, each image (`map:2.7`, `map:3.6`, `map:3.7`, `map:3.8`) has boost installed against the proper version of python.
___
*[.github/workflows/wheels.yml, line 35 at r3](https://reviewable.io/reviews/carla-simulator/map/60#-MehpClX7RkW6YXjWjqk:-MejbBSm9BsjFvZbsTm8:buv52re) ([raw file](https://github.com/carla-simulator/map/blob/47721b96e71ba652b21e165df3a8d531319f3b00/.github/workflows/wheels.yml#L35)):*
<details><summary><i>Previously, fabianoboril (Fabian Oboril) wrote…</i></summary><blockquote>

If we do not want to publish the wheels, we might also just publish them here and have automatic downloads in CARLA?
</blockquote></details>

Enabled publication of wheels to PyPI per release.
___
*[docker/Dockerfile, line 1 at r3](https://reviewable.io/reviews/carla-simulator/map/60#-Mehpypz9IC2b5RdRGIb:-MejeLQy80FL3iu-umoP:b-896fix) ([raw file](https://github.com/carla-simulator/map/blob/47721b96e71ba652b21e165df3a8d531319f3b00/docker/Dockerfile#L1)):*
<details><summary><i>Previously, fabianoboril (Fabian Oboril) wrote…</i></summary><blockquote>

This docker is only required for building as part of the github actions, or not? Maybe move to the github folder in this case
</blockquote></details>

Done.

**Review by fabianoboril — COMMENTED** [review]
> Reviewed 8 of 8 files at r4.
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/map/60)* status: all files reviewed, 3 unresolved discussions (waiting on @joel-mb)

___
*[.github/workflows/wheels.yml, line 14 at r3](https://reviewable.io/reviews/carla-simulator/map/60#-Mehp8Yt9vWf-1S1R-92:-Mf2clDs8gwhWfSuPpSd:bh0teuv) ([raw file](https://github.com/carla-simulator/map/blob/47721b96e71ba652b21e165df3a8d531319f3b00/.github/workflows/wheels.yml#L14)):*
<details><summary><i>Previously, joel-mb wrote…</i></summary><blockquote>

I created custom container images to avoid having to install all the dependencies during runtime. Also, each image (`map:2.7`, `map:3.6`, `map:3.7`, `map:3.8`) has boost installed against the proper version of python.
</blockquote></details>

Still the question is, who is maintaining this container? This seems like your own repo, so you plan to maintain this in case of future changes? 
___
*[.github/workflows/wheels.yml, line 5 at r4](https://reviewable.io/reviews/carla-simulator/map/60#-Mf2dhW69YXbQ6Z4e4lX:-Mf2dhW7AG-sBL8Ue_l-:b-65zcft) ([raw file](https://github.com/carla-simulator/map/blob/2b746267cbac5566b683a13ba9e749cc31277c7b/.github/workflows/wheels.yml#L5)):*
> ```YAML
> on:
>   release:
>     types: [published]
> ```

Maybe we should have also one job that tests the wheel build without pushing on each PR?

**Review by joel-mb — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/map/60)* status: 28 of 29 files reviewed, 3 unresolved discussions (waiting on @fabianoboril and @joel-mb)

___
*[.github/workflows/wheels.yml, line 14 at r3](https://reviewable.io/reviews/carla-simulator/map/60#-Mehp8Yt9vWf-1S1R-92:-MfDq6yPBNsOT1qrD3LS:b-2xeufq) ([raw file](https://github.com/carla-simulator/map/blob/47721b96e71ba652b21e165df3a8d531319f3b00/.github/workflows/wheels.yml#L14)):*
<details><summary><i>Previously, fabianoboril (Fabian Oboril) wrote…</i></summary><blockquote>

Still the question is, who is maintaining this container? This seems like your own repo, so you plan to maintain this in case of future changes? 
</blockquote></details>

Yes, I'm planning to upload these images to the official carlasim dockerhub as soon as possible (I don't have the credentials yet). I will maintain the images in the meantime. If you prefer, we can wait until the images are in the carlasim dockerhub before merging this.
___
*[.github/workflows/wheels.yml, line 5 at r4](https://reviewable.io/reviews/carla-simulator/map/60#-Mf2dhW69YXbQ6Z4e4lX:-MfDrCPM8ahfGlSSxPEV:b-896fja) ([raw file](https://github.com/carla-simulator/map/blob/2b746267cbac5566b683a13ba9e749cc31277c7b/.github/workflows/wheels.yml#L5)):*
<details><summary><i>Previously, fabianoboril (Fabian Oboril) wrote…</i></summary><blockquote>

Maybe we should have also one job that tests the wheel build without pushing on each PR?
</blockquote></details>

Done!

**Review by fabianoboril — APPROVED** [review]
> Reviewed 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/map/60)* status: all files reviewed, 1 unresolved discussion (waiting on @joel-mb)

**Review by berndgassmann — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/map/60)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @joel-mb)

**Pull request merged**
