### PR TITLE
Fix OpenDrive GeometryParamPoly3 calculation

### PR DESCRIPTION
**Pull request by berndgassmann**
Update version numbers to 2.4.7

---
This change is [Reviewable](https://reviewable.io/reviews/carla-simulator/map/64)

### CODE REVIEW

**Review by fabianoboril — CHANGES_REQUESTED** [review]
> Reviewed 17 of 17 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/map/64)* status: all files reviewed, 1 unresolved discussion (waiting on @berndgassmann)

___
*[ad_map_opendrive_reader/include/opendrive/types.hpp, line 20 at r1](https://reviewable.io/reviews/carla-simulator/map/64#-MhOIRo97Mcc_puWDdjE:-MhOIRoA5-zhFmg2-zQe:b-kmtmsr) ([raw file](https://github.com/carla-simulator/map/blob/f9aa1be6e0d0040e772c205b3588a27e8ecd1601/ad_map_opendrive_reader/include/opendrive/types.hpp#L20)):*
> ```cpp
> #include <memory>
> #include <set>
> #include <spdlog/spdlog.h>
> ```

Was that header missing before? The changes should not require the header

**Review by berndgassmann — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/map/64)* status: all files reviewed, 1 unresolved discussion (waiting on @fabianoboril)

___
*[ad_map_opendrive_reader/include/opendrive/types.hpp, line 20 at r1](https://reviewable.io/reviews/carla-simulator/map/64#-MhOIRo97Mcc_puWDdjE:-MhOJ2AW2VHcmm2EFWO_:b-uml9yy) ([raw file](https://github.com/carla-simulator/map/blob/f9aa1be6e0d0040e772c205b3588a27e8ecd1601/ad_map_opendrive_reader/include/opendrive/types.hpp#L20)):*
<details><summary><i>Previously, fabianoboril (Fabian Oboril) wrote…</i></summary><blockquote>

Was that header missing before? The changes should not require the header
</blockquote></details>

The log message in ensureValid() requires it now. Alternatively I could create a C++ file and move some implementations there (but loosing the inline speedup)

**Review by fabianoboril — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/map/64)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @berndgassmann)

**Comment by fabianoboril** [comment]
Let's wait for the map test, before merging. 

Maybe update the QGIS documentation and mention that pip install ad_map_access has to be performed before installing the plugin.

**Review by fabianoboril — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/map/64)* status: 16 of 27 files reviewed, 2 unresolved discussions (waiting on @berndgassmann and @fabianoboril)

___
*[.github/workflows/release_qgis_plugin.yml, line 20 at r3](https://reviewable.io/reviews/carla-simulator/map/64#-MhPCOZG1TuwQUl5PtU8:-MhPCOZG1TuwQUl5PtU9:bhig6lz) ([raw file](https://github.com/carla-simulator/map/blob/78a4c0170d90fcb8eff7523e218daa3cd393903e/.github/workflows/release_qgis_plugin.yml#L20)):*
> ```YAML
>         include:
>           - os: ubuntu-18.04
>             artifact_name: ad_map_access_qgis_ubuntu1804.zip
> ```

So we are no longer supporting Ubuntu 18.04?
___
*[.github/workflows/release_qgis_plugin.yml, line 31 at r3](https://reviewable.io/reviews/carla-simulator/map/64#-MhPCYoJ5Ql45z3sOPEu:-MhPCYoJ5Ql45z3sOPEv:b-2f80y1) ([raw file](https://github.com/carla-simulator/map/blob/e7fb84774ebb2c925d93475e402dea2f7551c2de/.github/workflows/release_qgis_plugin.yml#L31)):*
> ```YAML
>     - name: Build Package
>       run: |
>         cd install/ad_map_access_qgis/share/qgis/python/plugins/
> ```

WARNING:colcon.colcon_cmake.task.cmake.build:Could not run installation step for package 'ad_map_access_qgis' because it has no 'install' target

**Review by fabianoboril — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/map/64)* status: 16 of 27 files reviewed, 3 unresolved discussions (waiting on @berndgassmann and @fabianoboril)

___
*[tools/ad_map_access_qgis/CMakeLists.txt, line 14 at r3](https://reviewable.io/reviews/carla-simulator/map/64#-MhPCtlvBIsngzx2KEqK:-MhPCtlvBIsngzx2KEqL:bstqql) ([raw file](https://github.com/carla-simulator/map/blob/e7fb84774ebb2c925d93475e402dea2f7551c2de/tools/ad_map_access_qgis/CMakeLists.txt#L14)):*
> ```CMake
> include(GNUInstallDirs)
> 
> if(BUILD_PYTHON_BINDING)
> ```

Hm.. Does this evaluate to true? If it would, the install should work...

**Review by berndgassmann — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/map/64)* status: 16 of 27 files reviewed, 3 unresolved discussions (waiting on @fabianoboril)

___
*[.github/workflows/release_qgis_plugin.yml, line 20 at r3](https://reviewable.io/reviews/carla-simulator/map/64#-MhPCOZG1TuwQUl5PtU8:-MhPEpOO6avcIXGwbGKZ:b-7twkbt) ([raw file](https://github.com/carla-simulator/map/blob/78a4c0170d90fcb8eff7523e218daa3cd393903e/.github/workflows/release_qgis_plugin.yml#L20)):*
<details><summary><i>Previously, fabianoboril (Fabian Oboril) wrote…</i></summary><blockquote>

So we are no longer supporting Ubuntu 18.04?
</blockquote></details>

OS support depends on the wheels installed via pip. Here only the plugin folder is zipped, no binaries anymore.
___
*[.github/workflows/release_qgis_plugin.yml, line 31 at r3](https://reviewable.io/reviews/carla-simulator/map/64#-MhPCYoJ5Ql45z3sOPEu:-MhPF2tYBal3DLpH0CgN:b-1habdk) ([raw file](https://github.com/carla-simulator/map/blob/e7fb84774ebb2c925d93475e402dea2f7551c2de/.github/workflows/release_qgis_plugin.yml#L31)):*
<details><summary><i>Previously, fabianoboril (Fabian Oboril) wrote…</i></summary><blockquote>

WARNING:colcon.colcon_cmake.task.cmake.build:Could not run installation step for package 'ad_map_access_qgis' because it has no 'install' target
</blockquote></details>

Fixed now. I've removed the ad_map_access_qgis build from standard build if python build is not enabled to prevent from misuse. But I forgot to complete the update in colcon_python.meta.
___
*[tools/ad_map_access_qgis/CMakeLists.txt, line 14 at r3](https://reviewable.io/reviews/carla-simulator/map/64#-MhPCtlvBIsngzx2KEqK:-MhPFXZ22HUoWAVyfjwU:b-6jr5xg) ([raw file](https://github.com/carla-simulator/map/blob/e7fb84774ebb2c925d93475e402dea2f7551c2de/tools/ad_map_access_qgis/CMakeLists.txt#L14)):*
<details><summary><i>Previously, fabianoboril (Fabian Oboril) wrote…</i></summary><blockquote>

Hm.. Does this evaluate to true? If it would, the install should work...
</blockquote></details>

Obviously not. But now it does with latest commit ;-)

**Review by fabianoboril — APPROVED** [review]
> Reviewed 6 of 8 files at r2, 3 of 3 files at r3, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/map/64)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @berndgassmann)

**Pull request merged**
