### PR TITLE
Build documentation plain cmake update

### LINKED ISSUE #18: Python binding building incomplete on Ubuntu18.04
OS: Ubuntu18.04

Got error when building as follows:

```
➜  ad_map_access git:(master) cmake ../../ad_map_access -DCMAKE_INSTALL_PREFIX=../../install -DBUILD_PYTHON_BINDING=ON
```

The terminal is as follows:

```
-- Found Boost: /usr/include (found version "1.65.1") found components:  program_options filesystem system 
-- Found Boost: /usr/include (found version "1.65.1")  
-- Found PythonLibs: /usr/lib/x86_64-linux-gnu/libpython2.7.so (found suitable version "2.7.17", minimum required is "2") 
CMake Warning at /usr/local/lib/python3.6/dist-packages/cmake/data/share/cmake-3.15/Modules/FindBoost.cmake:2003 (message):
  No header defined for python-py27; skipping header check
Call Stack (most recent call first):
  /home/heyujie/Projects/map/cmake/python-binding.cmake:55 (find_package)
  python/CMakeLists.txt:29 (find_python_binding_packages)


-- Found Boost: /usr/include (found version "1.65.1") found components:  python-py27 
-- PythonLib 2 found. /usr/include/python2.7, /usr/lib/x86_64-linux-gnu/libpython2.7.so
-- Found PythonLibs: /usr/lib/x86_64-linux-gnu/libpython3.7m.so (found suitable version "3.7.8", minimum required is "3") 
CMake Warning at /usr/local/lib/python3.6/dist-packages/cmake/data/share/cmake-3.15/Modules/FindBoost.cmake:2003 (message):
  No header defined for python-py37; skipping header check
Call Stack (most recent call first):
  /home/heyujie/Projects/map/cmake/python-binding.cmake:84 (find_package)
  python/CMakeLists.txt:29 (find_python_binding_packages)


CMake Error at /usr/local/lib/python3.6/dist-packages/cmake/data/share/cmake-3.15/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find Boost (missing: python-py37) (found version "1.65.1")
Call Stack (most recent call first):
  /usr/local/lib/python3.6/dist-packages/cmake/data/share/cmake-3.15/Modules/FindPackageHandleStandardArgs.cmake:378 (_FPHSA_FAILURE_MESSAGE)
  /usr/local/lib/python3.6/dist-packages/cmake/data/share/cmake-3.15/Modules/FindBoost.cmake:2161 (find_package_handle_standard_args)
  /home/heyujie/Projects/map/cmake/python-binding.cmake:84 (find_package)
  python/CMakeLists.txt:29 (find_python_binding_packages)


-- Configuring incomplete, errors occurred!
See also "/home/heyujie/Projects/map/build/ad_map_access/CMakeFiles/CMakeOutput.log".
See also "/home/heyujie/Projects/map/build/ad_map_access/CMakeFiles/CMakeError.log".
```

BTW, any ideas to specify the Python version (preference: Python3.6)

Thanks in advance!

### PR DESCRIPTION
**Pull request by berndgassmann**
Build documentation update to make the plain cmake build more robust and
especially make repeated builds with -DBUILD_PYTHON_BINDING=ON working

Furthermore, improved user interface of python binding.

fix #18

---
This change is [Reviewable](https://reviewable.io/reviews/carla-simulator/map/19)

### CODE REVIEW

**Review by berndgassmann — COMMENTED** [review]
> Reviewed 18 of 18 files at r2.
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/map/19)* status: 15 of 18 files reviewed, all discussions resolved (waiting on @berndgassmann)

**Review by berndgassmann — COMMENTED** [review]
> Reviewed 2 of 3 files at r3, 2 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/map/19)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by fabianoboril — COMMENTED** [review]
> Reviewed 14 of 18 files at r2, 2 of 3 files at r3, 2 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/map/19)* status: all files reviewed, 1 unresolved discussion (waiting on @berndgassmann)

___
*[doc/ad_physics/ad_physics_python.md, line 14 at r4](https://reviewable.io/reviews/carla-simulator/map/19#-MFZAm4p95pJj0ssHFjP:-MFZAm4p95pJj0ssHFjQ:blxuedk) ([raw file](https://github.com/carla-simulator/map/blob/04b6e96c058e57f2bc7581b48f441b1e723afd91/doc/ad_physics/ad_physics_python.md#L14)):*
> ```Markdown
> Python package and use it as any other Python module.
> ```bash
>  map$>  export PYTHONPATH=$PYTHONPATH:<path/to/>install/ad_physics/lib/python3
> ```

We could align this with official directories using python2.7 or python 3.5/3.6/3.7 (depending on which version we want to claim support for).

**Review by berndgassmann — COMMENTED** [review]
> Reviewed 9 of 9 files at r5.
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/map/19)* status: all files reviewed, 1 unresolved discussion (waiting on @fabianoboril)

___
*[doc/ad_physics/ad_physics_python.md, line 14 at r4](https://reviewable.io/reviews/carla-simulator/map/19#-MFZAm4p95pJj0ssHFjP:-MFZj90NAoakSJNJLKBU:b-896fix) ([raw file](https://github.com/carla-simulator/map/blob/04b6e96c058e57f2bc7581b48f441b1e723afd91/doc/ad_physics/ad_physics_python.md#L14)):*
<details><summary><i>Previously, fabianoboril (Fabian Oboril) wrote…</i></summary><blockquote>

We could align this with official directories using python2.7 or python 3.5/3.6/3.7 (depending on which version we want to claim support for).
</blockquote></details>

Done.

**Review by fabianoboril — CHANGES_REQUESTED** [review]
Let's wait for the other bug fix to come

> Reviewed 9 of 9 files at r5.
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/map/19#-:-MFdumFq16FrSmIrE60R:b-p8fgpd)* status: all files reviewed, 1 unresolved discussion (waiting on @fabianoboril)

**Comment by felipecode** [comment]
I am having this error when running the tests.
I reinstalled from cmake following the build instructions from this branch.

======================================================================
ERROR: test_interface (__main__.AdMapAccessPythonTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "ad_map_access/python/tests/interface_test.py", line 33, in test_interface
    self.assertTrue(ad.map.access.init("test_files/TPK.adm.txt"))
AttributeError: module 'ad.map' has no attribute 'access'

----------------------------------------------------------------------
Ran 1 test in 0.000s

Also the import is a bit strange

it imports ad.map directly and then uses ad.physics.

**Comment by berndgassmann** [comment]
> I am having this error when running the tests.
> I reinstalled from cmake following the build instructions from this branch.
> 
> ## ======================================================================
> ERROR: test_interface (**main**.AdMapAccessPythonTest)
> Traceback (most recent call last):
> File "ad_map_access/python/tests/interface_test.py", line 33, in test_interface
> self.assertTrue(ad.map.access.init("test_files/TPK.adm.txt"))
> AttributeError: module 'ad.map' has no attribute 'access'
> 
> Ran 1 test in 0.000s
> 
> Also the import is a bit strange
> 
> it imports ad.map directly and then uses ad.physics.

Since ad.map depends on the types defined within ad.physics it has to import ad.physics upfront, otherwise there will be unresolved types; therefore ad.physics should be accessible out of the box. But it complains on ad.map.access which also should be imported beforehand 
https://github.com/carla-simulator/map/pull/19/files#diff-cc193fed92e70ad6bbc181dd50c8bd10

Did you set the pythonpath correctly? Because while going down that interface change -- within the pull request --- the python things will now get installed in subfolders named in respect to the concrete python version e.g. ad_map_access_python$>  export PYTHONPATH=$PYTHONPATH:<path/to/>install/ad_physics/lib/python3.6:<path/to/>install/ad_map_access/lib/python3.6
That allows to build multiple python versions at once... which opens the door for deployment via pip in future.

Because this is changing the interface on python level, we will wait with merging this change until we are sure it works together with CARLA. So I've to check if it works also with static linking (to be able to remove the LD_LIBRARY_PATH settings which won't work inside the CARLA-egg). And we will have to increase the major version number due to the interface change. 

Therefore, I've split the documentation change part from this pull request and merged it together with some other improvements into the 2.2.0 release yesterday.

This pull request will then be rebased, but first I've to work the way through to make it CARLA-egg compatible...

Hope this helps

**Comment by berndgassmann** [comment]
@felipecode 
As I am just trying the static build, what you might also missing in your setup is setting of the LD_LIBRARY_PATH that the shared C++ libraries can be found. By using a static build this one at least will be eliminated.
I hope to provide soon an update of this with static build.
In the end, it's adding (-DBUILD_SHARED_LIBS=OFF) to the cmake commands, but requires to enforce the SHARED linkage within the python/CMakeList.txt (otherwhise python cannot load the code)...

**Comment by berndgassmann** [comment]
This pull request is replace by the new one only focusing on the interface change on python side.
The documentation part is already in release 2.2.1 included.

**Pull request closed without merging**
