### PR TITLE
OpenDRIVE reader: complete geometry import

### PR DESCRIPTION
**Pull request by berndgassmann**
- The parser code under ad_map_opendrive_reader was updated in-line with
the CARLA commit 3e2b29ecc38922e6a0a41653febe0d647df81d83
- Enabled additional set of compiler warnings and fixed these
- Consider shape and superelevation from lateralProfile including keep
on level flag
- Consider lane height entries
- Consider pRange value from param poly3 geometry
- Ensure small final positioning errors on sampling of the border points
- Fixed issues with inaccuracies on open drive import

Change-Id: I8c844e0aea6996589f2c9b5e569efa81cd006b82

---
This change is [Reviewable](https://reviewable.io/reviews/carla-simulator/map/59)

### CODE REVIEW

**Review by fabianoboril — CHANGES_REQUESTED** [review]
> Reviewed 31 of 31 files at r1.
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/map/59)* status: all files reviewed, 2 unresolved discussions (waiting on @berndgassmann)

___
*[ad_map_opendrive_reader/CMakeLists.txt, line 17 at r1](https://reviewable.io/reviews/carla-simulator/map/59#-Me5YNf54pQfGz8_VMwQ:-Me5YNf54pQfGz8_VMwR:bshj1wb) ([raw file](https://github.com/carla-simulator/map/blob/2525acd44e71c035ffa73b1bd75fb431d598fce9/ad_map_opendrive_reader/CMakeLists.txt#L17)):*
> ```CMake
> include(../cmake/testing.cmake)
> include(../cmake/warnings.cmake)
> include(../cmake/apidoc.cmake)
> ```

This causes the doc build to fail complaining about a missing doxygen.in file
___
*[ad_map_opendrive_reader/src/parser/JunctionParser.cpp, line 6 at r1](https://reviewable.io/reviews/carla-simulator/map/59#-Me5Yo4-3Txca162O0OH:-Me5Yo4-3Txca162O0OI:b-8k883n) ([raw file](https://github.com/carla-simulator/map/blob/2525acd44e71c035ffa73b1bd75fb431d598fce9/ad_map_opendrive_reader/src/parser/JunctionParser.cpp#L6)):*
> ```cpp
>  * Copyright (c) 2017 Computer Vision Center (CVC) at the Universitat Autonoma
>  * de Barcelona (UAB).
>  * Copyright (C) 2019-2020 Intel Corporation
> ```

2021?

**Review by berndgassmann — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/map/59)* status: 26 of 32 files reviewed, 2 unresolved discussions (waiting on @fabianoboril and @glopezdiest)

___
*[ad_map_opendrive_reader/CMakeLists.txt, line 17 at r1](https://reviewable.io/reviews/carla-simulator/map/59#-Me5YNf54pQfGz8_VMwQ:-Me5eEzI2hJJM6gmoo92:bgc1ufs) ([raw file](https://github.com/carla-simulator/map/blob/2525acd44e71c035ffa73b1bd75fb431d598fce9/ad_map_opendrive_reader/CMakeLists.txt#L17)):*
<details><summary><i>Previously, fabianoboril (Fabian Oboril) wrote…</i></summary><blockquote>

This causes the doc build to fail complaining about a missing doxygen.in file
</blockquote></details>

Added a Doygen file. But docu is currently not deployed as it is in each case a bit poor ...
___
*[ad_map_opendrive_reader/src/parser/JunctionParser.cpp, line 6 at r1](https://reviewable.io/reviews/carla-simulator/map/59#-Me5Yo4-3Txca162O0OH:-Me5e_Vj5CoFyDdxYxOQ:b-rku753) ([raw file](https://github.com/carla-simulator/map/blob/2525acd44e71c035ffa73b1bd75fb431d598fce9/ad_map_opendrive_reader/src/parser/JunctionParser.cpp#L6)):*
<details><summary><i>Previously, fabianoboril (Fabian Oboril) wrote…</i></summary><blockquote>

2021?
</blockquote></details>

Done also for the other files where last changes were noted in 2020

**Comment by glopezdiest** [comment]
Regarding the CARLA towns, all the errors I reported seem to be fixed.

The unconnected roads at Town04 and Town06 are now connected, which can both be seen in the QGIS plugin as well as the route planner correctly creating those routes.

For the altitude, it has also improved, resulting in the correct one. For example, Town04 no longer has that linear altitude parsing at the bridge.

**Review by fabianoboril — APPROVED** [review]
> Reviewed 1 of 1 files at r2, 5 of 5 files at r3.
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/map/59)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @glopezdiest)

**Review by fabianoboril — APPROVED** [review]
> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/map/59)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @glopezdiest)

**Pull request merged**
